
interface ComponentCode {
  preview: string;
  html: string;
  css: string;
  fullcode: string;
}

// Simple component registry with example components
const componentRegistry: Record<string, ComponentCode> = {
  "Button": {
    preview: '<button class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors">Primary Button</button>',
    html: '<button class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors">\n  Primary Button\n</button>',
    css: '.button-primary {\n  background-color: rgb(59, 130, 246);\n  color: white;\n  padding: 0.5rem 1rem;\n  border-radius: 0.375rem;\n  transition-property: background-color;\n  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);\n  transition-duration: 150ms;\n}\n\n.button-primary:hover {\n  background-color: rgb(37, 99, 235);\n}',
    fullcode: 'import React from "react";\n\nexport const Button = () => {\n  return (\n    <button className="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors">\n      Primary Button\n    </button>\n  );\n};'
  },
  "Card": {
    preview: '<div class="max-w-sm rounded overflow-hidden shadow-lg bg-white"><div class="px-6 py-4"><div class="font-bold text-xl mb-2">Card Title</div><p class="text-gray-700 text-base">Card description with some text content.</p></div></div>',
    html: '<div class="max-w-sm rounded overflow-hidden shadow-lg bg-white">\n  <div class="px-6 py-4">\n    <div class="font-bold text-xl mb-2">Card Title</div>\n    <p class="text-gray-700 text-base">Card description with some text content.</p>\n  </div>\n</div>',
    css: '.card {\n  max-width: 24rem;\n  border-radius: 0.25rem;\n  overflow: hidden;\n  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);\n  background-color: white;\n}\n\n.card-body {\n  padding: 1.5rem 1.5rem;\n}\n\n.card-title {\n  font-weight: 700;\n  font-size: 1.25rem;\n  margin-bottom: 0.5rem;\n}\n\n.card-text {\n  color: #4b5563;\n  font-size: 1rem;\n}',
    fullcode: 'import React from "react";\n\nexport const Card = () => {\n  return (\n    <div className="max-w-sm rounded overflow-hidden shadow-lg bg-white">\n      <div className="px-6 py-4">\n        <div className="font-bold text-xl mb-2">Card Title</div>\n        <p className="text-gray-700 text-base">Card description with some text content.</p>\n      </div>\n    </div>\n  );\n};'
  },
  "Input": {
    preview: '<input type="text" class="px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" placeholder="Enter text...">',
    html: '<input type="text" class="px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" placeholder="Enter text...">',
    css: '.input {\n  padding: 0.5rem 1rem;\n  border: 1px solid #d1d5db;\n  border-radius: 0.375rem;\n}\n\n.input:focus {\n  outline: none;\n  --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);\n  --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color);\n  box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow, 0 0 #0000);\n  --tw-ring-color: rgb(59, 130, 246);\n  border-color: transparent;\n}',
    fullcode: 'import React from "react";\n\nexport const Input = () => {\n  return (\n    <input\n      type="text"\n      className="px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"\n      placeholder="Enter text..."\n    />\n  );\n};'
  },
  "Dropdown": {
    preview: '<div class="relative inline-block text-left"><button class="inline-flex justify-center w-full rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none">Options</button></div>',
    html: '<div class="relative inline-block text-left">\n  <button class="inline-flex justify-center w-full rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none">Options</button>\n</div>',
    css: '.dropdown {\n  position: relative;\n  display: inline-block;\n  text-align: left;\n}\n\n.dropdown-button {\n  display: inline-flex;\n  justify-content: center;\n  width: 100%;\n  border-radius: 0.375rem;\n  border: 1px solid #d1d5db;\n  box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05);\n  padding: 0.5rem 1rem;\n  background-color: white;\n  font-size: 0.875rem;\n  font-weight: 500;\n  color: #374151;\n}\n\n.dropdown-button:hover {\n  background-color: #f9fafb;\n}\n\n.dropdown-button:focus {\n  outline: none;\n}',
    fullcode: 'import React, { useState } from "react";\n\nexport const Dropdown = () => {\n  const [isOpen, setIsOpen] = useState(false);\n\n  return (\n    <div className="relative inline-block text-left">\n      <button\n        onClick={() => setIsOpen(!isOpen)}\n        className="inline-flex justify-center w-full rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none"\n      >\n        Options\n      </button>\n      \n      {isOpen && (\n        <div className="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5">\n          <div className="py-1" role="menu" aria-orientation="vertical">\n            <a href="#" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">Option 1</a>\n            <a href="#" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">Option 2</a>\n            <a href="#" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">Option 3</a>\n          </div>\n        </div>\n      )}\n    </div>\n  );\n};'
  },
  "Modal": {
    preview: '<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center"><div class="bg-white rounded-lg p-6 max-w-md mx-auto"><h3 class="text-lg font-medium mb-4">Modal Title</h3><p class="mb-4">Modal content goes here.</p><button class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">Close</button></div></div>',
    html: '<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">\n  <div class="bg-white rounded-lg p-6 max-w-md mx-auto">\n    <h3 class="text-lg font-medium mb-4">Modal Title</h3>\n    <p class="mb-4">Modal content goes here.</p>\n    <button class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">Close</button>\n  </div>\n</div>',
    css: '.modal-backdrop {\n  position: fixed;\n  inset: 0;\n  background-color: rgba(0, 0, 0, 0.5);\n  display: flex;\n  align-items: center;\n  justify-content: center;\n}\n\n.modal-content {\n  background-color: white;\n  border-radius: 0.5rem;\n  padding: 1.5rem;\n  max-width: 28rem;\n  margin: 0 auto;\n}\n\n.modal-title {\n  font-size: 1.125rem;\n  font-weight: 500;\n  margin-bottom: 1rem;\n}\n\n.modal-body {\n  margin-bottom: 1rem;\n}\n\n.modal-button {\n  padding: 0.5rem 1rem;\n  background-color: rgb(59, 130, 246);\n  color: white;\n  border-radius: 0.25rem;\n}\n\n.modal-button:hover {\n  background-color: rgb(37, 99, 235);\n}',
    fullcode: 'import React, { useState } from "react";\n\nexport const Modal = () => {\n  const [isOpen, setIsOpen] = useState(false);\n\n  return (\n    <>\n      <button\n        onClick={() => setIsOpen(true)}\n        className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"\n      >\n        Open Modal\n      </button>\n\n      {isOpen && (\n        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">\n          <div className="bg-white rounded-lg p-6 max-w-md mx-auto">\n            <h3 className="text-lg font-medium mb-4">Modal Title</h3>\n            <p className="mb-4">Modal content goes here.</p>\n            <button\n              className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"\n              onClick={() => setIsOpen(false)}\n            >\n              Close\n            </button>\n          </div>\n        </div>\n      )}\n    </>\n  );\n};'
  },
  "Tabs": {
    preview: '<div class="border-b border-gray-200"><nav class="-mb-px flex" aria-label="Tabs"><a href="#" class="border-blue-500 text-blue-600 border-b-2 py-4 px-4 text-sm font-medium">Tab 1</a><a href="#" class="border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 border-b-2 py-4 px-4 text-sm font-medium">Tab 2</a><a href="#" class="border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 border-b-2 py-4 px-4 text-sm font-medium">Tab 3</a></nav></div>',
    html: '<div class="border-b border-gray-200">\n  <nav class="-mb-px flex" aria-label="Tabs">\n    <a href="#" class="border-blue-500 text-blue-600 border-b-2 py-4 px-4 text-sm font-medium">Tab 1</a>\n    <a href="#" class="border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 border-b-2 py-4 px-4 text-sm font-medium">Tab 2</a>\n    <a href="#" class="border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 border-b-2 py-4 px-4 text-sm font-medium">Tab 3</a>\n  </nav>\n</div>',
    css: '.tabs-container {\n  border-bottom: 1px solid #e5e7eb;\n}\n\n.tabs-nav {\n  display: flex;\n  margin-bottom: -1px;\n}\n\n.tab {\n  border-bottom: 2px solid transparent;\n  padding: 1rem 1rem;\n  font-size: 0.875rem;\n  font-weight: 500;\n  color: #6b7280;\n}\n\n.tab:hover {\n  color: #374151;\n  border-bottom-color: #d1d5db;\n}\n\n.tab.active {\n  border-bottom-color: rgb(59, 130, 246);\n  color: rgb(37, 99, 235);\n}',
    fullcode: 'import React, { useState } from "react";\n\nexport const Tabs = () => {\n  const [activeTab, setActiveTab] = useState(0);\n  const tabs = ["Tab 1", "Tab 2", "Tab 3"];\n\n  return (\n    <div>\n      <div className="border-b border-gray-200">\n        <nav className="-mb-px flex" aria-label="Tabs">\n          {tabs.map((tab, index) => (\n            <a\n              key={index}\n              href="#"\n              onClick={(e) => {\n                e.preventDefault();\n                setActiveTab(index);\n              }}\n              className={`\n                ${index === activeTab\n                  ? "border-blue-500 text-blue-600"\n                  : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"}\n                border-b-2 py-4 px-4 text-sm font-medium\n              `}\n            >\n              {tab}\n            </a>\n          ))}\n        </nav>\n      </div>\n      <div className="py-4">\n        {activeTab === 0 && <div>Content for Tab 1</div>}\n        {activeTab === 1 && <div>Content for Tab 2</div>}\n        {activeTab === 2 && <div>Content for Tab 3</div>}\n      </div>\n    </div>\n  );\n};'
  },
  "Table": {
    preview: '<table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th><th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Title</th></tr></thead><tbody class="bg-white divide-y divide-gray-200"><tr><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Jane Cooper</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">Regional Paradigm Technician</td></tr></tbody></table>',
    html: '<table class="min-w-full divide-y divide-gray-200">\n  <thead class="bg-gray-50">\n    <tr>\n      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>\n      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Title</th>\n    </tr>\n  </thead>\n  <tbody class="bg-white divide-y divide-gray-200">\n    <tr>\n      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Jane Cooper</td>\n      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">Regional Paradigm Technician</td>\n    </tr>\n  </tbody>\n</table>',
    css: '.table {\n  min-width: 100%;\n  border-collapse: collapse;\n  border-spacing: 0;\n}\n\n.table thead {\n  background-color: #f9fafb;\n}\n\n.table thead th {\n  padding: 0.75rem 1.5rem;\n  text-align: left;\n  font-size: 0.75rem;\n  font-weight: 500;\n  color: #6b7280;\n  text-transform: uppercase;\n  letter-spacing: 0.05em;\n}\n\n.table tbody {\n  background-color: white;\n}\n\n.table tbody tr {\n  border-top: 1px solid #e5e7eb;\n}\n\n.table tbody td {\n  padding: 1rem 1.5rem;\n  white-space: nowrap;\n  font-size: 0.875rem;\n}\n\n.table tbody td:first-child {\n  font-weight: 500;\n  color: #111827;\n}\n\n.table tbody td:not(:first-child) {\n  color: #6b7280;\n}',
    fullcode: 'import React from "react";\n\nexport const Table = () => {\n  const people = [\n    { name: "Jane Cooper", title: "Regional Paradigm Technician" },\n    { name: "Cody Fisher", title: "Product Directives Officer" },\n    { name: "Esther Howard", title: "Forward Response Developer" },\n  ];\n\n  return (\n    <div className="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">\n      <table className="min-w-full divide-y divide-gray-200">\n        <thead className="bg-gray-50">\n          <tr>\n            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">\n              Name\n            </th>\n            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">\n              Title\n            </th>\n          </tr>\n        </thead>\n        <tbody className="bg-white divide-y divide-gray-200">\n          {people.map((person) => (\n            <tr key={person.name}>\n              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">\n                {person.name}\n              </td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">\n                {person.title}\n              </td>\n            </tr>\n          ))}\n        </tbody>\n      </table>\n    </div>\n  );\n};'
  },
  "Toggle": {
    preview: '<button type="button" class="bg-gray-200 relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none" role="switch" aria-checked="false"><span class="translate-x-0 pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out"></span></button>',
    html: '<button type="button" class="bg-gray-200 relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none" role="switch" aria-checked="false">\n  <span class="translate-x-0 pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out"></span>\n</button>',
    css: '.toggle {\n  background-color: #e5e7eb;\n  position: relative;\n  display: inline-flex;\n  height: 1.5rem;\n  width: 2.75rem;\n  flex-shrink: 0;\n  cursor: pointer;\n  border-radius: 9999px;\n  border: 2px solid transparent;\n  transition-property: background-color;\n  transition-duration: 200ms;\n  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);\n}\n\n.toggle:focus {\n  outline: none;\n}\n\n.toggle-on {\n  background-color: #3b82f6;\n}\n\n.toggle-handle {\n  translate: 0px;\n  pointer-events: none;\n  display: inline-block;\n  height: 1.25rem;\n  width: 1.25rem;\n  transform: translateX(0);\n  border-radius: 9999px;\n  background-color: white;\n  box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05);\n  transition-property: transform;\n  transition-duration: 200ms;\n  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);\n}\n\n.toggle-on .toggle-handle {\n  transform: translateX(100%);\n}',
    fullcode: 'import React, { useState } from "react";\n\nexport const Toggle = () => {\n  const [enabled, setEnabled] = useState(false);\n\n  return (\n    <button\n      type="button"\n      onClick={() => setEnabled(!enabled)}\n      className={`${enabled ? "bg-blue-500" : "bg-gray-200"} relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none`}\n      role="switch"\n      aria-checked={enabled}\n    >\n      <span\n        className={`${enabled ? "translate-x-5" : "translate-x-0"} pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out`}\n      />\n    </button>\n  );\n};'
  }
};

export const getComponentCode = (name: string): ComponentCode | null => {
  return componentRegistry[name] || null;
};
