import React from 'react';
import '@/styles/animated-checklist.css';

export const AnimatedChecklist: React.FC = () => {
  return (
    <div className="relative flex justify-center w-full">
      <div className="w-full max-w-[260px] bg-[#f8fafc] rounded-2xl shadow-lg p-6 grid grid-cols-[30px_auto] items-center gap-y-[18px] font-sans">
        <input defaultChecked defaultValue={1} name="r" type="checkbox" id="01" className="appearance-none relative h-5 w-5 border-2 border-gray-300 rounded-full cursor-pointer bg-[#f8fafc] grid place-items-center transition-all duration-200 ease-out hover:border-[#0c85d0] hover:scale-105 checked:bg-[#1da1f2] checked:border-[#1da1f2] checked:shadow-[0_0_0_2px_rgba(29,161,242,0.2)] checked:before:content-[''] checked:before:absolute checked:before:top-[2px] checked:before:left-[6px] checked:before:w-[5px] checked:before:h-[10px] checked:before:border-r-2 checked:before:border-b-2 checked:before:border-white checked:before:rotate-45 checked:before:animate-[checkmark_0.3s_cubic-bezier(0.05,0.7,0.1,1)_forwards]" />
        <label htmlFor="01" className="text-[#1e293b] cursor-pointer flex items-center w-full transition-colors duration-300 font-medium tracking-tight whitespace-nowrap overflow-hidden text-ellipsis pr-2.5 hover:text-gray-600 peer-checked:text-[#a0aec0] peer-checked:animate-[move_0.3s_ease_0.1s_forwards]">List Item 1</label>
        
        <input defaultValue={2} name="r" type="checkbox" id="02" className="appearance-none relative h-5 w-5 border-2 border-gray-300 rounded-full cursor-pointer bg-[#f8fafc] grid place-items-center transition-all duration-200 ease-out hover:border-[#0c85d0] hover:scale-105 checked:bg-[#1da1f2] checked:border-[#1da1f2] checked:shadow-[0_0_0_2px_rgba(29,161,242,0.2)] checked:before:content-[''] checked:before:absolute checked:before:top-[2px] checked:before:left-[6px] checked:before:w-[5px] checked:before:h-[10px] checked:before:border-r-2 checked:before:border-b-2 checked:before:border-white checked:before:rotate-45 checked:before:animate-[checkmark_0.3s_cubic-bezier(0.05,0.7,0.1,1)_forwards]" />
        <label htmlFor="02" className="text-[#1e293b] cursor-pointer flex items-center w-full transition-colors duration-300 font-medium tracking-tight whitespace-nowrap overflow-hidden text-ellipsis pr-2.5 hover:text-gray-600 peer-checked:text-[#a0aec0] peer-checked:animate-[move_0.3s_ease_0.1s_forwards]">List Item 2</label>
        
        <input defaultValue={3} name="r" type="checkbox" id="03" className="appearance-none relative h-5 w-5 border-2 border-gray-300 rounded-full cursor-pointer bg-[#f8fafc] grid place-items-center transition-all duration-200 ease-out hover:border-[#0c85d0] hover:scale-105 checked:bg-[#1da1f2] checked:border-[#1da1f2] checked:shadow-[0_0_0_2px_rgba(29,161,242,0.2)] checked:before:content-[''] checked:before:absolute checked:before:top-[2px] checked:before:left-[6px] checked:before:w-[5px] checked:before:h-[10px] checked:before:border-r-2 checked:before:border-b-2 checked:before:border-white checked:before:rotate-45 checked:before:animate-[checkmark_0.3s_cubic-bezier(0.05,0.7,0.1,1)_forwards]" />
        <label htmlFor="03" className="text-[#1e293b] cursor-pointer flex items-center w-full transition-colors duration-300 font-medium tracking-tight whitespace-nowrap overflow-hidden text-ellipsis pr-2.5 hover:text-gray-600 peer-checked:text-[#a0aec0] peer-checked:animate-[move_0.3s_ease_0.1s_forwards]">List Item 3</label>
        
        <input defaultValue={4} name="r" type="checkbox" id="04" className="appearance-none relative h-5 w-5 border-2 border-gray-300 rounded-full cursor-pointer bg-[#f8fafc] grid place-items-center transition-all duration-200 ease-out hover:border-[#0c85d0] hover:scale-105 checked:bg-[#1da1f2] checked:border-[#1da1f2] checked:shadow-[0_0_0_2px_rgba(29,161,242,0.2)] checked:before:content-[''] checked:before:absolute checked:before:top-[2px] checked:before:left-[6px] checked:before:w-[5px] checked:before:h-[10px] checked:before:border-r-2 checked:before:border-b-2 checked:before:border-white checked:before:rotate-45 checked:before:animate-[checkmark_0.3s_cubic-bezier(0.05,0.7,0.1,1)_forwards]" />
        <label htmlFor="04" className="text-[#1e293b] cursor-pointer flex items-center w-full transition-colors duration-300 font-medium tracking-tight whitespace-nowrap overflow-hidden text-ellipsis pr-2.5 hover:text-gray-600 peer-checked:text-[#a0aec0] peer-checked:animate-[move_0.3s_ease_0.1s_forwards]">List Item 4</label>
        
        <input defaultValue={5} name="r" type="checkbox" id="05" className="appearance-none relative h-5 w-5 border-2 border-gray-300 rounded-full cursor-pointer bg-[#f8fafc] grid place-items-center transition-all duration-200 ease-out hover:border-[#0c85d0] hover:scale-105 checked:bg-[#1da1f2] checked:border-[#1da1f2] checked:shadow-[0_0_0_2px_rgba(29,161,242,0.2)] checked:before:content-[''] checked:before:absolute checked:before:top-[2px] checked:before:left-[6px] checked:before:w-[5px] checked:before:h-[10px] checked:before:border-r-2 checked:before:border-b-2 checked:before:border-white checked:before:rotate-45 checked:before:animate-[checkmark_0.3s_cubic-bezier(0.05,0.7,0.1,1)_forwards]" />
        <label htmlFor="05" className="text-[#1e293b] cursor-pointer flex items-center w-full transition-colors duration-300 font-medium tracking-tight whitespace-nowrap overflow-hidden text-ellipsis pr-2.5 hover:text-gray-600 peer-checked:text-[#a0aec0] peer-checked:animate-[move_0.3s_ease_0.1s_forwards]">List Item 5</label>
      </div>
    </div>
  );
};

export default AnimatedChecklist; 